name = "PovertyAndInequalityMeasures"
uuid = "582645c0-90fa-497a-98b9-936b80116c29"
authors = ["Graham Stark"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
